#!/usr/bin/env php
<?php
defined ('YII_DEBUG') or define('YII_DEBUG', true);
defined ('YII_ENV') or define('YII_ENV', 'dev');

require (__DIR__ . '/../vendor/autoload.php');
require (__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');

// note: bootatrap-locals need to be pulled in before bootstraps
require (__DIR__ . '/common/config/bootstrap-local.php');
require (__DIR__ . '/console/config/bootstrap-local.php');
require (__DIR__ . '/common/config/bootstrap.php');
require (__DIR__ . '/console/config/bootstrap.php');

$config = yii\helpers\ArrayHelper::merge(
  require (__DIR__ . '/common/config/main.php'),
  require (__DIR__ . '/common/config/main-local.php'),
  require (__DIR__ . '/console/config/main.php'),
  require (__DIR__ . '/console/config/main-local.php')
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
